task:
  name: NeoverseN1
  arm_container:
    image: python:3.11.7
    cpu: 8
  compile_script:
  - python3 -m pip install numpy==1.26.0
  - echo 'import time; import numpy as np; time.sleep(30); np.show_config(); quit();'|python3
