macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-xcode:latest

task:
  name: AppleM1/LLVM
  compile_script:
  - brew install llvm
  - export PATH=/opt/homebrew/opt/llvm/bin:$PATH
  - export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  - export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
  - make TARGET=VORTEX USE_OPENMP=1 CC=clang

task:
  name: AppleM1/LLVM x86_64 xbuild
  compile_script:
  - brew install llvm
  - export PATH=/opt/homebrew/opt/llvm/bin:$PATH
  - export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  - export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
  - make TARGET=HASWELL USE_OPENMP=1 CC="/opt/homebrew/opt/llvm/bin/clang -arch x86_64"
#  always:
#    config_artifacts:
#      path: "*conf*"
#      type: text/plain
#  lib_artifacts:
#    path: "libopenblas*"
#    type: application/octet-streamm


task:
  name: Graviton2
  arm_container:
    image: node:latest
  compile_script:
  - make
  

windows_task:
  name: Windows/LLVM16
  windows_container:
    image:cirrusci/windowsservercore:2019
  install_script: 
    - choco install -y llvm
    - choco install -y cmake
    - choco install -y ninja
    - cmake . -S build -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release
