macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:15

task:
  name: AppleM1/GCC/xcode15
  compile_script:
  - brew install gcc@13
  - export PATH=/opt/homebrew/bin:$PATH
  - export LDFLAGS="-L/opt/homebrew/lib"
  - export CPPFLAGS="-I/opt/homebrew/include"
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
  - ctest
