macos_instance:
  image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
task:
  name: AppleM1/LLVM armv7-androidndk xbuild
  compile_script:
  - brew install --cask android-ndk
  - export ANDROID_NDK_HOME="/System/Volumes/Data/opt/homebrew/share/android-ndk"
  - ls -lR /opt/homebrew/share/android-ndk/
  - #find / -name "*android-ndk*"
  - #find /opt/homebrew -name "armv7a-linux-androideabi*-ranlib"
  - #export CC=/System/Volumes/Data/opt/homebrew/share/android-ndk/prebuilt/27b/AndroidNDK*.app/Contents/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi23-clang
  - ämake TARGET=ARMV7 ARM_SOFTFP_ABI=1 NUM_THREADS=32 HOSTCC=clang NOFORTRAN=1 RANLIB="ls -l"
  always:
    config_artifacts:
      path: "*conf*"
      type: text/plain




