# XXX: Precise is already deprecated, new default is Trusty.
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
dist: focal
sudo: true
language: c

matrix:
  include:
    - &test-ubuntu
#      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - gfortran
            - g++
            - wget
      os: linux
      arch: ppc64le
      before_script: &common-before
        - COMMON_FLAGS="TARGET=POWER8"
      script:
        - travis_wait 40 make QUIET_MAKE=1 $COMMON_FLAGS $BTYPE
        - wget -q https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-ppc64le.sh
        - sh ./Anaconda3-2022.05-Linux-ppc64le.sh -b -p $HOME/conda
        - eval "$($HOME/conda/bin/conda shell.bash hook)"
        - conda init
        - #conda create condas
        - conda activate #condas
        - conda install -y astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses hypothesis expecttest
        - conda install -y pytorch
        - #git clone --recursive https://github.com/pytorch/pytorch
        - #export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
        - #cd pytorch
        - #python3 setup.py install
        - #mv test test.orig
        - wget -q https://www.mkroeker.com/pytorchsrc.tbz
        - travis_wait 25 tar jxf pytorchsrc.tbz
        - wget -q https://www.mkroeker.com/pytorchbin.tbz
        - cd /
        - sudo tar jxvf /home/travis/build/xianyi/OpenBLAS/pytorchbin.tbz
        - cd -
        - #cd pytorch/build
        - #rm CMakeCache.txt
        - #wget https://www.mkroeker.com/CMakeCache.txt
        - #cd ..
        - #python3 setup.py install
        - cd pytorch/test
        - sed -i -e "s/@onlyCUDA//g" -e "s/@largeTensorTest('12GB')//g" test_nn.py
        - python3 test_nn.py TestNNDeviceTypeCPU.test_conv_large_cpu
        - cp ../../libopenblas.so $HOME/conda/lib
        - cp ../../libopenblas.so.0 $HOME/conda/lib
        - python3 test_nn.py TestNNDeviceTypeCPU.test_conv_large_cpu
      env:
        # for matrix annotation only
        - TARGET_BOX=PPC64LE_LINUX
        - BTYPE="BINARY=64 USE_OPENMP=1"

        
# whitelist
branches:
  only:
    - master
    - develop

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8a6e4470a0cebd090344
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
