# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
    echo "FROM openblas/alpine:arm32
        COPY . /tmp/openblas
        RUN mkdir /tmp/openblas/build                             &&  \
            cd /tmp/openblas/build                                &&  \
            CC=gcc cmake -D DYNAMIC_ARCH=OFF                          \
                                 -D TARGET=ARMV6                      \
                                 -D NOFORTRAN=ON                      \
                                 -D BUILD_SHARED_LIBS=ON              \
                                 -D BUILD_WITHOUT_LAPACK=ON           \
                                 -D BUILD_WITHOUT_CBLAS=ON            \
                                 -D CMAKE_BUILD_TYPE=Release ../  &&  \
            cmake --build ." > Dockerfile
    docker build .
  displayName: Run ARMV6 docker build

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
